version: '3.8'

services:
  backend:
    build:
      context: ./src   # Updated to reflect that the Dockerfile is under 'src'
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    env_file:
      - ./src/sample.env  # Adjusted path to the .env file under 'src'
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./src/evaluation_plots:/app/evaluation_plots
      - ./src/trace.pdf:/app/trace.pdf
      - ./src/votes.json:/app/votes.json
    restart: unless-stopped
    networks:
      - coolify

networks:
  coolify:
    external: true
