version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    env_file:
      - sample.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./evaluation_plots:/app/evaluation_plots
      - ./trace.pdf:/app/trace.pdf
      - ./votes.json:/app/votes.json
    restart: unless-stopped
    networks:
      - coolify

networks:
  coolify:
    external: true
